### ISSUE TITLE
src/DS3/Framework/HTTP/ - Unification de l'interface Request / Response

### ISSUE THREAD

**Issue by skeggib** [domotique-s3/dbCharts#12]
#### Problème

La classe `Request` utilise des attributs privés avec des getters, alors que `Response` utilise plutôt un attribut public. Cela porte à confusion chez l'utilisateur de ces deux classes

#### Solution

Au choix \:
1. Utiliser des getters partout
2. Utiliser les attributs publics

**Comment by palra** [comment]
See ed9eb40
