### ISSUE TITLE
ParameterBag::remove() - Retourner la valeur supprimée

### ISSUE THREAD

**Issue by skeggib** [domotique-s3/dbCharts#23]
Dans le méthode remove(string $key) de ParameterBag, il serai pas mal de retourne la valeur de la clé supprimée.

**Comment by drattak** [comment]
Retourner la valeur de la clé supprimée, ou false si la clé n'existe pas, non ?

**Comment by skeggib** [comment]
Ouaip

Le lun. 25 janv. 2016 13:16, Vincent Emile <notifications@github.com> a
écrit :

**Comment by palra** [comment]
Closed by 14ca013a
